name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}

    steps: &ci-steps
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Linux UI deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3-xlib scrot

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest -q

      - name: Build Windows EXE
        if: runner.os == 'Windows'
        run: |
          powershell ./build_win.bat
        continue-on-error: true

      - name: Upload Windows artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: BookEaseFormatter.exe
          path: dist/BookEaseFormatter.exe

  second-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps: *ci-steps
